stages:
  - build
  - deploy

build_eureka_server:
  stage: build
  image: maven:3.8.5-openjdk-17
  script:
    - echo "Building eureka-server..."
    - cd eureka-server
    - mvn clean install
    - echo "Finished building eureka-server."
  artifacts:
    name: eureka_server_build
    paths:
      - eureka-server/target/eureka-server-0.0.1-SNAPSHOT.jar
  rules:
    - changes:
        - eureka-server/**/*

deploy_eureka_server:
  stage: deploy
  dependencies:
    - build_eureka_server
  image: ubuntu
  before_script:
    - apt-get update && apt-get install -y openssh-client
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - touch ~/.ssh/config
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - ssh-keyscan -H "$DEPLOY_SERVER_IP" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - echo "Deploying eureka-server"
    - scp eureka-server/target/eureka-server-0.0.1-SNAPSHOT.jar ubuntu@ec2-54.211.227.50.compute-1.amazonaws.com:/home/ubuntu
    - echo "Finished deploying eureka-server."