server:
  port: 8090

eureka:
  instance:
    hostname: 18.234.78.224
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://18.234.78.224:8761/eureka

spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: ms-users
          uri: lb://ms-users
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=2
        - id: ms-ticket
          uri: lb://ms-ticket
          predicates:
            - Path=/api/ticket/**
          filters:
            - StripPrefix=2
        - id: ms-place
          uri: lb://ms-place
          predicates:
            - Path=/api/place/**
          filters:
            - StripPrefix=2
        - id: ms-events
          uri: lb://ms-events
          predicates:
            - Path=/api/events/**
          filters:
            - StripPrefix=2
