spring:
  application:
    name: eureka-server

server:
  port: 8761

eureka:
  instance:
    hostname: 3.88.142.25
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    fetch-registry: false
    register-with-eureka: false
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://3.88.142.25:8761/eureka