spring:
  application:
    name: eureka-server

server:
  port: 8761

eureka:
  instance:
    hostname: 54.91.250.44
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    fetch-registry: false
    register-with-eureka: false
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://54.91.250.44:8761/eureka