spring:
  application:
    name: ms-ticket
  datasource:
    url: jdbc:mysql://localhost:3306/ticketreck
    username: root
    password: contra
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/ticketrek

email:
  username: ticketrekpi@gmail.com
  password: xueb lzgg bjmh plxv

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8085
