spring:
  application:
    name: ms-ticket
  datasource:
    url: jdbc:mysql://ticketreck-db-mysql.cf4gakmqo0vw.us-east-1.rds.amazonaws.com:3306/ticketreckDB
    username: admin
    password: xWwbbN9sYkKlLJJb6jz5
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://54.232.143.80:8080/realms/ticketrek

email:
  username: ticketrekpi@gmail.com
  password: xueb lzgg bjmh plxv

eureka:
  instance:
    hostname: 54.232.143.80
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://54.232.143.80:8761/eureka

server:
  port: 8085
