spring:
  application:
    name: ms-users
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://54.232.143.80:8080/realms/ticketrek

eureka:
  instance:
    hostname: 54.232.143.80
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://54.232.143.80:8761/eureka

server:
  port: 8082

backend:
  keycloak:
    serverUrl: http://54.232.143.80:8080
    realm: ticketrek
    clientId: ms-users
    clientSecret: GmHSNdo6VmRq6Kpm9vl7GbfO4njbVOlT